version: "3.6"
services:
  postgresql:
    image: "postgres:15"
    ports:
      - "6543:5432"
    restart: always
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_DB: pggen
      POSTGRES_PASSWORD: hunter2
      POSTGRES_USER: postgres
