name: Test
on: [push, pull_request]
jobs:
  test:
    name: go test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: pggen
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: hunter2
        ports:
          - 5555:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - run: go test ./...
      - run: go test --tags=acceptance_test ./...
        env:
          DOCKER_API_VERSION: 1.39
